package com.sam.markdownreader.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// A hand-tuned vibrant palette: electric violet primary, raspberry secondary,
// burnt-amber tertiary. High chroma throughout, per M3 Expressive guidance.

val VibrantLightColors = lightColorScheme(
    primary = Color(0xFF5F0EE0),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFE8DDFF),
    onPrimaryContainer = Color(0xFF1E0060),
    secondary = Color(0xFFA90F6E),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFD8E7),
    onSecondaryContainer = Color(0xFF3B0028),
    tertiary = Color(0xFF9A4500),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDBC8),
    onTertiaryContainer = Color(0xFF321200),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFDF7FF),
    onBackground = Color(0xFF1C1B20),
    surface = Color(0xFFFDF7FF),
    onSurface = Color(0xFF1C1B20),
    surfaceVariant = Color(0xFFE8E0F0),
    onSurfaceVariant = Color(0xFF4A4356),
    outline = Color(0xFF7B7488),
    outlineVariant = Color(0xFFCCC3D8),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF313036),
    inverseOnSurface = Color(0xFFF4EFF6),
    inversePrimary = Color(0xFFCDBDFF),
    surfaceTint = Color(0xFF5F0EE0),
    surfaceDim = Color(0xFFDDD8E4),
    surfaceBright = Color(0xFFFDF7FF),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF7F1FB),
    surfaceContainer = Color(0xFFF1EBF5),
    surfaceContainerHigh = Color(0xFFEBE5F0),
    surfaceContainerHighest = Color(0xFFE5DFEA),
)

val VibrantDarkColors = darkColorScheme(
    primary = Color(0xFFCDBDFF),
    onPrimary = Color(0xFF33009F),
    primaryContainer = Color(0xFF4A00C8),
    onPrimaryContainer = Color(0xFFE8DDFF),
    secondary = Color(0xFFFFAFD1),
    onSecondary = Color(0xFF5D0040),
    secondaryContainer = Color(0xFF83004F),
    onSecondaryContainer = Color(0xFFFFD8E7),
    tertiary = Color(0xFFFFB68A),
    onTertiary = Color(0xFF522300),
    tertiaryContainer = Color(0xFF753300),
    onTertiaryContainer = Color(0xFFFFDBC8),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF141218),
    onBackground = Color(0xFFE6E0EA),
    surface = Color(0xFF141218),
    onSurface = Color(0xFFE6E0EA),
    surfaceVariant = Color(0xFF4A4356),
    onSurfaceVariant = Color(0xFFCCC3D8),
    outline = Color(0xFF958DA2),
    outlineVariant = Color(0xFF4A4356),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFE6E0EA),
    inverseOnSurface = Color(0xFF313036),
    inversePrimary = Color(0xFF5F0EE0),
    surfaceTint = Color(0xFFCDBDFF),
    surfaceDim = Color(0xFF141218),
    surfaceBright = Color(0xFF3B383F),
    surfaceContainerLowest = Color(0xFF0F0D13),
    surfaceContainerLow = Color(0xFF1C1A21),
    surfaceContainer = Color(0xFF211E26),
    surfaceContainerHigh = Color(0xFF2B2830),
    surfaceContainerHighest = Color(0xFF36333B),
)
